# Understanding data
Throughout this notebook, I am going to explore the data files and undestand what they mean in a superficial way.

<hr />

In [2]:
import pandas as pd

master = pd.read_csv('../data/raw/critical_minerals_supply_master.csv')
dictionary = pd.read_csv('../data/raw/data_dictionary.csv')
reference = pd.read_csv('../data/raw/minerals_reference.csv')

In [3]:
master.head()

,year,mineral,country,is_rare_earth,end_use,mine_production_tonnes,production_share_pct,reserves_tonnes,years_of_reserves,refined_share_pct,price_usd_per_tonne,demand_growth_pct,export_control_active,hhi,top_country_share_pct,supply_risk_score,high_supply_risk,disruption,disruption_next_year
0,2015,Antimony,Australia,0,flame_ret,5853.8,3.97,123696.0,21.1,3.18,11340.82,10.4,0,0.3796,57.75,28.2,0,0,0.0
1,2016,Antimony,Australia,0,flame_ret,6385.8,3.95,215205.0,33.7,3.16,11738.55,7.9,0,0.3549,52.35,29.1,0,0,0.0
2,2017,Antimony,Australia,0,flame_ret,6342.4,3.75,379889.0,59.9,3.00,10595.20,7.1,0,0.3604,52.93,23.3,0,0,0.0
3,2018,Antimony,Australia,0,flame_ret,7178.8,4.09,86793.0,12.1,3.27,11535.79,9.2,0,0.3784,58.15,41.5,0,0,0.0
4,2019,Antimony,Australia,0,flame_ret,6516.7,3.89,167755.0,25.7,3.11,11603.62,6.0,0,0.3880,57.97,28.9,0,0,0.0

In [4]:
dictionary.head()

          column    type                                        description
0           year     int                                   Year (2015-2026)
1        mineral  string              Critical mineral / rare-earth element
2        country  string                                  Producing country
3  is_rare_earth     int                          1 if a rare-earth element
4        end_use  string  Primary end use (battery, magnet, semiconducto...

In [5]:
reference.head()

      mineral  is_rare_earth    end_use  avg_top_country_share  n_producers
0    Antimony              0  flame_ret                   55.0            5
1      Cerium              1   catalyst                   62.4            5
2      Cobalt              0    battery                   70.6            7
3      Copper              0       grid                   34.0            9
4  Dysprosium              1     magnet                   85.8            4

<hr />

## Dataset's Dictionary

In [6]:
dictionary.head(19)

,column,type,description
0,year,int,Year (2015-2026)
1,mineral,string,Critical mineral / rare-earth element
2,country,string,Producing country
3,is_rare_earth,int,1 if a rare-earth element
4,end_use,string,"Primary end use (battery, magnet, semiconducto..."
5,mine_production_tonnes,float,Simulated mine production (metric tonnes)
6,production_share_pct,float,Country share of that mineral world production...
7,reserves_tonnes,float,Simulated reserves (metric tonnes)
8,years_of_reserves,float,Reserves / annual production (years of supply)
9,refined_share_pct,float,Country share of refining/processing (%) — mor...
10,price_usd_per_tonne,float,"Simulated mineral price (USD/tonne), realistic..."
11,demand_growth_pct,float,Annual demand growth for the end-use segment (%)
12,export_control_active,int,1 if the country had export controls on this m...
13,hhi,float,Herfindahl-Hirschman index of production conce...
14,top_country_share_pct,float,Largest producer share for that mineral-year (%)
15,supply_risk_score,float,COMPUTED analytical supply-risk index (0-100) ...
16,high_supply_risk,int,1 if supply_risk_score in top 30% (analytical ...
17,disruption,int,1 if a supply disruption occurred that year (c...
18,disruption_next_year,float,ML TARGET (forward-looking): 1 if disruption o...

In [7]:
print(dictionary['description'].iloc[12] + '\n')
print(dictionary['description'].iloc[13]+ '\n')
print(dictionary['description'].iloc[15]+ '\n')
print(dictionary['description'].iloc[16]+ '\n')
print(dictionary['description'].iloc[17]+ '\n')
print(dictionary['description'].iloc[18]+ '\n')

1 if the country had export controls on this mineral that year

Herfindahl-Hirschman index of production concentration (mineral-year)

COMPUTED analytical supply-risk index (0-100) from concentration/geopolitics/controls

1 if supply_risk_score in top 30% (analytical label, derived)

1 if a supply disruption occurred that year (control onset / share collapse / price spike)

ML TARGET (forward-looking): 1 if disruption occurs next year; NaN for 2026

### Observations
* hhi -> Simple mesure that mesures market concentration and how much competition exists between companies in an industry

* Production share -> Mesures the productor's contribution of the all market, that is to say, wich percentage of how much of the total market's production is made by just one producer 



<hr />

## Master dataset

In [8]:
information = {
    'Missing values: ':master.isna().sum(),
    'Percentage: ':master.isna().mean()
}

print(pd.DataFrame(information))

                        Missing values:   Percentage:
year                                   0      0.000000
mineral                                0      0.000000
country                                0      0.000000
is_rare_earth                          0      0.000000
end_use                                0      0.000000
mine_production_tonnes                 0      0.000000
production_share_pct                   0      0.000000
reserves_tonnes                        0      0.000000
years_of_reserves                      0      0.000000
refined_share_pct                      0      0.000000
price_usd_per_tonne                    0      0.000000
demand_growth_pct                      0      0.000000
export_control_active                  0      0.000000
hhi                                    0      0.000000
top_country_share_pct                  0      0.000000
supply_risk_score                      0      0.000000
high_supply_risk                       0      0.000000
disruption                             0      0.000000
disruption_next_year                 129      0.083333

Here we can observe that there are almost no missing values, the only ones that does exist comes from **disruption_next_year**, wich is meant to be like that because those are the predict goal values.

In [9]:
master.head()

,year,mineral,country,is_rare_earth,end_use,mine_production_tonnes,production_share_pct,reserves_tonnes,years_of_reserves,refined_share_pct,price_usd_per_tonne,demand_growth_pct,export_control_active,hhi,top_country_share_pct,supply_risk_score,high_supply_risk,disruption,disruption_next_year
0,2015,Antimony,Australia,0,flame_ret,5853.8,3.97,123696.0,21.1,3.18,11340.82,10.4,0,0.3796,57.75,28.2,0,0,0.0
1,2016,Antimony,Australia,0,flame_ret,6385.8,3.95,215205.0,33.7,3.16,11738.55,7.9,0,0.3549,52.35,29.1,0,0,0.0
2,2017,Antimony,Australia,0,flame_ret,6342.4,3.75,379889.0,59.9,3.00,10595.20,7.1,0,0.3604,52.93,23.3,0,0,0.0
3,2018,Antimony,Australia,0,flame_ret,7178.8,4.09,86793.0,12.1,3.27,11535.79,9.2,0,0.3784,58.15,41.5,0,0,0.0
4,2019,Antimony,Australia,0,flame_ret,6516.7,3.89,167755.0,25.7,3.11,11603.62,6.0,0,0.3880,57.97,28.9,0,0,0.0

In [10]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 1548 entries, 0 to 1547
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    1548 non-null   int64
 1   mineral                 1548 non-null   str
 2   country                 1548 non-null   str
 3   is_rare_earth           1548 non-null   int64
 4   end_use                 1548 non-null   str
 5   mine_production_tonnes  1548 non-null   float64
 6   production_share_pct    1548 non-null   float64
 7   reserves_tonnes         1548 non-null   float64
 8   years_of_reserves       1548 non-null   float64
 9   refined_share_pct       1548 non-null   float64
 10  price_usd_per_tonne     1548 non-null   float64
 11  demand_growth_pct       1548 non-null   float64
 12  export_control_active   1548 non-null   int64
 13  hhi                     1548 non-null   float64
 14  top_country_share_pct   1548 non-null   float64
 15  supply_risk_score       1548 non-null   float64
 16  high_supply_risk        1548 non-null   int64
 17  disruption              1548 non-null   int64
 18  disruption_next_year    1419 non-null   float64
dtypes: float64(11), int64(5), str(3)
memory usage: 229.9 KB

In [11]:
print(master['end_use'].unique())

<StringArray>
[    'flame_ret',      'catalyst',       'battery',          'grid',
        'magnet', 'semiconductor',       'display',         'alloy',
     'capacitor',        'solder',      'phosphor']
Length: 11, dtype: str

In [ ]:
## Is 'reserved_tonnes made out of int values?
master['reserves_tonnes_int_true'] = master['reserves_tonnes'].apply(lambda x: x.is_integer())

information_reserves_tones = {
    'int quantity': master['reserves_tonnes_int_true'].sum(),
    'Percentage_of_int': str(master['reserves_tonnes_int_true'].mean() * 100) + '%'
}

print(pd.DataFrame(information_reserves_tones, index=[0]))

   int quantity Percentage_of_int
0          1548            100.0%

In [23]:
# Whats the maximun years_of_reserved

print('Max year: ',master['years_of_reserves'].max())

Max year:  60.0

Based on the meaning of the different variables and the actual data type wich containt the data, we can do some transformations on the data, in order to have a better control on the expected data values. This will be much more worth on the data engineering pipeline.

### Proposed changes:
* year -> int16
* is rare_earth -> bool
* end_use -> Categorize the different values with numbers and store the meaning in the dictionary
* reserved_tonnes -> Change the datatype to int
* high_supply_risk, disruption, disruption_next_year -> Bool